version: "3.8"

services:

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_market

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - springboot-mysql-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  springboot-app:
    build: .
    container_name: springboot-app
    restart: always

    ports:
      - "8085:8081"

    depends_on:
      mysql-container:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/stock_market?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    networks:
      - springboot-mysql-network

networks:
  springboot-mysql-network:
    driver: bridge

volumes:
  mysql-data:
