server.port=8081

spring.datasource.url=jdbc:mysql://mysql-container:3306/stock_market?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=boragigouri9@gmail.com
spring.mail.password=mdsi kfrc abxe xdsz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

admin.email=admin@gmail.com
admin.password=admin123

stock.api.key=YFIX7CJ4UGJJBU6Z

razor-pay.api.key=rzp_test_SixBOhL5b4QEgU
razor-pay.api.secret=VzMCVSjwsvfBukfV9N7Uos12

platformPercentage=0.04

server.servlet.session.tracking-modes=cookie
